# Generated by Django 5.2.7 on 2025-11-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('line', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('opening_time', models.CharField(default='05:00', max_length=5)),
                ('closing_time', models.CharField(default='23:00', max_length=5)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operativa'), ('MAINTENANCE', 'Mantenimiento'), ('CONSTRUCTION', 'Construcción'), ('CLOSED', 'Cerrada')], default='OPERATIONAL', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stations/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
                'ordering': ['line', 'name'],
            },
        ),
    ]
